name: Strategy
on: push

jobs:
  testing_strategy:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        number_to_log: [1,2,3]
        include:
          - os: windows-latest
            number_to_log: 5
        exclude:
          - os: ubuntu-latest
            number_to_log: 1
      fail-fast: true

    runs-on: ubuntu-latest
    steps:
      - name: testing the strategy
        run: echo ${{ matrix.numbers_to_log }}
      - name: testing the namin
        env:
          person: bako
        run: echo $person