name: test

on:
  schedule:
    - cron: "0/5 * * * *"
  pull_request:
    branches:
      - main
    types: [reopened, opened]
  push:
    branches:
      - test_branch
 
jobs:
  canceling_the_jobs:
    runs-on: macos-10.15
    steps:
      - name: Git - Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.3.app
      - name: using github checkout action
        uses: actions/checkout@v1
      - name: run the test
        run: fastlane test
        
           
