name: test

on: push
 
jobs:
  canceling_the_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        run: echo "hello world"
      - name: step two
        run: echo "hello world again"
      - name: pythone
        run: |
            import platform
            print(platform.processsor())
        shell: python      
        
           
