name: test

on:
  schedule:
    - cron: "0/5 * * * *"
  pull_request:
    branches:
      - main
    types: [reopened, opened]
  push:
    branches:
      - test_branch
 
jobs:
  canceling_the_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        run: echo "hello world"
      - name: step two
        run: echo "hello world again"
      - name: pythone
        run: |
            import platform
            print(platform.processor())  
        shell: python   
      - name: using github checkout action
        uses: actions/checkout@v1
      - name: run the test
        run: fastlane test
        
           
