name: test

on:
  schedule:
    - cron: "0/5 * * * *"
  pull_request:
    types: [opened, reopened]
 
jobs:
  canceling_the_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: step one
        run: echo "hello world"
      - name: step two
        run: echo "hello world again"
      - name: pythone
        run: |
            import platform
            print(platform.processor())  
        shell: python   
      - name: using github checkout action
        uses: actions/checkout@v1
      - name: lising the items
        run: 
          pwd
          ls -a
        
           
